import type { Category } from "./schema";

/** Shape of one seed product. Tamil fields are optional. */
export type ProductSeed = {
  name: string;
  nameTa?: string;
  brand: string;
  category: Category;
  subcategory: string;
  price: number;
  mrp: number;
  rating: number;
  ratingCount: number;
  colors: string[];
  sizes: string[];
  tags: string[];
  photoId?: string;
  notes: string;
  notesTa?: string;
};

export const SEED_PRODUCTS: ProductSeed[] = [
  {
    name: "Rani Handblock Cotton Kurta",
    nameTa: "ராணி கைத்தட்டு பருத்தி குர்தா",
    brand: "Boutiq Studio",
    category: "kurtas",
    subcategory: "Cotton Kurtas",
    price: 1690, mrp: 2450, rating: 4.8, ratingCount: 312,
    colors: ["Indigo", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["bestseller"],
    photoId: "photo-1583394838336-acd977736f90",
    notes: "Hand-block printed mul cotton with wooden buttons and side slits.",
    notesTa: "கைத்தட்டு அச்சிடப்பட்ட மரப் பொத்தான்கள் கொண்ட மென்மையான பருத்தி குர்தா.",
  },
  {
    name: "Meenakari Chanderi Kurta",
    nameTa: "மீனாகாரி சாந்தேரி குர்தா",
    brand: "Boutiq Studio",
    category: "kurtas",
    subcategory: "Silk Kurtas",
    price: 2890, mrp: 4200, rating: 4.7, ratingCount: 164,
    colors: ["Emerald", "Maroon"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["new"],
    photoId: "photo-1610030469983-98e550d6193c",
    notes: "Chanderi silk-cotton with gota detailing along the yoke.",
    notesTa: "தோள்பட்டையில் கோட்டா வேலைப்பாடு கொண்ட சாந்தேரி பட்டு-பருத்தி குர்தா.",
  },
  {
    name: "Gulmohar Angrakha Kurta",
    nameTa: "குல்மோகர் அங்கரகா குர்தா",
    brand: "Atelier Gul",
    category: "kurtas",
    subcategory: "Angrakha",
    price: 2340, mrp: 3400, rating: 4.6, ratingCount: 98,
    colors: ["Mustard", "Rust"],
    sizes: ["XS", "S", "M", "L"],
    tags: [],
    photoId: "photo-1594633312681-425c7b97ccd1",
    notes: "Tie-up angrakha silhouette in soft handloom cotton.",
    notesTa: "மென்மையான கைத்தறி பருத்தியில் கட்டும் அங்கரகா வடிவ குர்தா.",
  },
  {
    name: "Naintara Chikankari Kurta",
    nameTa: "நைனதாரா சிகான்காரி குர்தா",
    brand: "Awadh Label",
    category: "kurtas",
    subcategory: "Chikankari",
    price: 3190, mrp: 4600, rating: 4.9, ratingCount: 76,
    colors: ["Ivory", "Powder Blue"],
    sizes: ["S", "M", "L"],
    tags: ["bestseller", "new"],
    photoId: "photo-1596755094514-f87e34085b2c",
    notes: "Lucknowi chikankari hand embroidery on georgette.",
    notesTa: "ஜார்ஜெட் துணியில் லக்னௌ சிகான்காரி கைவேலைப்பாடு குர்தா.",
  },
  {
    name: "Banarasi Silk Saree",
    nameTa: "பனாரஸ் பட்டுச் சேலை",
    brand: "Vastraa House",
    category: "sarees",
    subcategory: "Banarasi",
    price: 6490, mrp: 9200, rating: 4.8, ratingCount: 142,
    colors: ["Deep Maroon", "Antique Gold"],
    sizes: ["Free Size"],
    tags: ["bestseller"],
    photoId: "photo-1583496661160-fb5886a0aaaa",
    notes: "Pure Katan silk with real zari brocade and unstitched blouse piece.",
    notesTa: "உண்மையான ஜரி வேலைப்பாடு கொண்ட தூய கதான் பட்டுச் சேலை; ரவிக்கை துணி உடன்.",
  },
  {
    name: "Kanjivaram Temple-Border Saree",
    nameTa: "காஞ்சிபுரம் கோவில்-எல்லை சேலை",
    brand: "Vastraa House",
    category: "sarees",
    subcategory: "Kanjivaram",
    price: 8990, mrp: 12800, rating: 4.9, ratingCount: 61,
    colors: ["Emerald", "Rani Pink"],
    sizes: ["Free Size"],
    tags: [],
    photoId: "photo-1610652492500-ded49ceeb378",
    notes: "Woven temple border in korvai technique, silk mark certified.",
    notesTa: "கோவில் எல்லை நெசவு, சில்க் மார்க் சான்றளிக்கப்பட்ட காஞ்சி பட்டுச் சேலை.",
  },
  {
    name: "Chanderi Everyday Saree",
    nameTa: "சாந்தேரி தினசரி சேலை",
    brand: "Boutiq Studio",
    category: "sarees",
    subcategory: "Chanderi",
    price: 3890, mrp: 5400, rating: 4.6, ratingCount: 87,
    colors: ["Blush", "Sage"],
    sizes: ["Free Size"],
    tags: ["new"],
    photoId: "photo-1585487000160-6ebcfceb0d03",
    notes: "Featherlight chanderi with scattered buttis and gold selvedge.",
    notesTa: "எடை குறைந்த சாந்தேரி; சிதறல் புட்டா மற்றும் பொன்னிற ஓரம்.",
  },
  {
    name: "Linen Sunset Saree",
    nameTa: "லினன் சூரியாஸ்தமய சேலை",
    brand: "Atelier Gul",
    category: "sarees",
    subcategory: "Linen",
    price: 3290, mrp: 4600, rating: 4.5, ratingCount: 54,
    colors: ["Terracotta", "Sand"],
    sizes: ["Free Size"],
    tags: [],
    photoId: "photo-1601924994987-69e26d50dc26",
    notes: "Handloom linen with a wide terracotta pallu, pre-pleated fall.",
    notesTa: "அகலமான சிவப்பு-மண் நிற பல்லு கொண்ட கைத்தறி லினன் சேலை.",
  },
  {
    name: "Zohra Co-ord Kurta Set",
    nameTa: "சோஹ்ரா இணை குர்தா அமைப்பு",
    brand: "Boutiq Studio",
    category: "sets",
    subcategory: "Kurta Sets",
    price: 3990, mrp: 5800, rating: 4.7, ratingCount: 118,
    colors: ["Sage", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["bestseller", "new"],
    photoId: "photo-1572804013309-59a88b7e92f1",
    notes: "Three-piece kurta, palazzo and organza dupatta in tone-on-tone.",
    notesTa: "மூன்று பகுதி குர்தா, பலாஸோ மற்றும் ஒர்கன்சா துப்பட்டா.",
  },
  {
    name: "Ambar Sharara Set",
    nameTa: "அம்பர் ஷராரா அமைப்பு",
    brand: "Awadh Label",
    category: "sets",
    subcategory: "Sharara Sets",
    price: 5490, mrp: 7900, rating: 4.8, ratingCount: 73,
    colors: ["Powder Blue", "Champagne"],
    sizes: ["S", "M", "L"],
    tags: ["trending"],
    photoId: "photo-1620921575116-fb8902865f81",
    notes: "Sequinned short kurta with flared sharara and net dupatta.",
    notesTa: "முத்து வேலைப்பாடு கொண்ட குறுகிய குர்தா, விரிந்த ஷராரா, நெட் துப்பட்டா.",
  },
  {
    name: "Suhana Anarkali Set",
    nameTa: "சுஹானா அனார்கலி அமைப்பு",
    brand: "Atelier Gul",
    category: "sets",
    subcategory: "Anarkali",
    price: 4690, mrp: 6800, rating: 4.6, ratingCount: 92,
    colors: ["Wine", "Dusty Rose"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: [],
    photoId: "photo-1522771930-78848d9293e8",
    notes: "Floor-length anarkali with churidar and banarasi dupatta.",
    notesTa: "தரை தொடு நீள அனார்கலி; சுடிதார் மற்றும் பனாரஸ் துப்பட்டா.",
  },
  {
    name: "Ila Cotton Lounge Set",
    nameTa: "இளா பருத்தி லவுஞ்ச் அமைப்பு",
    brand: "Boutiq Studio",
    category: "sets",
    subcategory: "Lounge Sets",
    price: 2190, mrp: 3100, rating: 4.5, ratingCount: 143,
    colors: ["Oat", "Powder Blue"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["new"],
    photoId: "photo-1617137968427-85924c800a22",
    notes: "Breathable mul-cotton set for slow mornings and evenings in.",
    notesTa: "காற்றோட்டமான மல்மல் அமைப்பு; மெதுவான காலை, மாலை நேரங்களுக்கு ஏற்றது.",
  },
  {
    name: "Mehr Velvet Dress",
    nameTa: "மெஹர் வெல்வெட் கவுன்",
    brand: "Atelier Gul",
    category: "dresses",
    subcategory: "Velvet",
    price: 4290, mrp: 6200, rating: 4.7, ratingCount: 66,
    colors: ["Wine", "Ink"],
    sizes: ["XS", "S", "M", "L"],
    tags: ["trending"],
    photoId: "photo-1509631179647-0177331693ae",
    notes: "Bias-cut velvet with embellished cuffs, festive evenings.",
    notesTa: "விருந்து மாலை நேரங்களுக்கு ஏற்ற வெல்வெட் கவுன்; அலங்கரிக்கப்பட்ட கைகள்.",
  },
  {
    name: "Falak Indigo Midi Dress",
    nameTa: "ஃபாலக் இன்டிகோ மிடி கவுன்",
    brand: "Boutiq Studio",
    category: "dresses",
    subcategory: "Midi",
    price: 2790, mrp: 3900, rating: 4.6, ratingCount: 104,
    colors: ["Indigo", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: [],
    photoId: "photo-1496747611176-843222e1e57c",
    notes: "Hand-dyed indigo midi with wooden bead ties and pockets.",
    notesTa: "மர மணி கட்டுகள், பாக்கெட்டுகள் கொண்ட கையால் சாயமிடப்பட்ட மிடி கவுன்.",
  },
  {
    name: "Noor Tiered Maxi Dress",
    nameTa: "நூர் படிநிலை மேக்ஸி கவுன்",
    brand: "Awadh Label",
    category: "dresses",
    subcategory: "Maxi",
    price: 3490, mrp: 5000, rating: 4.8, ratingCount: 58,
    colors: ["Blush", "Sage"],
    sizes: ["S", "M", "L"],
    tags: ["new"],
    photoId: "photo-1515372039744-b8f02a3ae446",
    notes: "Tiered georgette maxi with scalloped hem and smocked bodice.",
    notesTa: "செதில் விளிம்பு, ஸ்மோக்ட் மேலங்கி கொண்ட படிநிலை ஜார்ஜெட் மேக்ஸி கவுன்.",
  },
  {
    name: "Aurelia Wrap Dress",
    nameTa: "ஆரெலியா ரேப் கவுன்",
    brand: "Vastraa House",
    category: "dresses",
    subcategory: "Wrap",
    price: 3090, mrp: 4400, rating: 4.5, ratingCount: 47,
    colors: ["Maroon", "Sand"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: [],
    photoId: "photo-1591085686350-798c0f9faa7f",
    notes: "Silk-blend wrap dress with a hand-embroidered belt.",
    notesTa: "கை வேலைப்பாட்டு பெல்ட் கொண்ட பட்டுக் கலப்பு ரேப் கவுன்.",
  },
];
